### PR TITLE
Hunter Gazebo Package Development 

### PR DESCRIPTION
**Pull request by PabloEspejeLS**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update

### CODE REVIEW

**Review by marc-hanheide — CHANGES_REQUESTED** [review]
Hi @PabloEspejeLS 

pinging also @ibrahimhroob 

I would want a quick discussion here. 

This is adding packages to this fork. It *may* be better to do as I suggested in https://github.com/LCAS/hunter_robot/issues/3#issuecomment-2034950220

I.e., to leave this repository as a fork of https://github.com/agilexrobotics/hunter_ros2 with *no* added packages and only a few specific additions for L-CAS. This will make maintenance with regard to [upstream](https://github.com/agilexrobotics/hunter_ros2) much easier in my view. I would suggest that the changes (new packages) `hunter_controller`, `hunter_description` and `hunter_gazebo` go into https://github.com/LCAS/hunter_robot (as originally planned I think). Please see https://github.com/LCAS/hunter_robot/pull/5 which was designed to remove the packages that should indeed only be in this repository.

I would then suggest to add a package `hunter_bringup` to https://github.com/LCAS/hunter_robot that 
1. depends on the other `hunter_*` packages
2. contains all the config files (tmule, yaml,...) and launch files that in this PR were added in various places 

Happy to discuss

**Comment by marc-hanheide** [comment]
Also pinging @LeonardoGuevara to chip in if needed.

**Comment by ibrahimhroob** [comment]
Hi @marc-hanheide , yes I agree with your suggestions, this started to get a little bit messy and needs cleaning up

**Comment by ibrahimhroob** [comment]
Hi @PabloEspejeLS, as Marc suggested we will leave the forked repo as it is and we will keep making the changes on https://github.com/LCAS/hunter_robot and make the forked repo a dependent package. Sorry will have to reject this PR.

**Comment by ibrahimhroob** [comment]
@PabloEspejeLS , Can you please update your changes to https://github.com/LCAS/hunter_robot, I will review them and refactor the code, and please delete the unnecessary branches. I did make https://github.com/LCAS/hunter_ros2 as a submodule, however, this is not the correct way to do it, I will fix that.

**Comment by marc-hanheide** [comment]
@ibrahimhroob , is this done now?

**Comment by ibrahimhroob** [comment]
yes it is done

**Pull request closed without merging**
