### PR TITLE
Create ros-ci.yml

### PR DESCRIPTION
**Pull request by marc-hanheide**
added CI

### CODE REVIEW

**Comment by marc-hanheide** [comment]
superseded by #2

**Comment by ibrahimhroob** [comment]
Hi @marc-hanheide , if this branch is not needed can we delete it? thanks

**Comment by marc-hanheide** [comment]
which branch?

**Comment by ibrahimhroob** [comment]
this one: [marc-hanheide-ros-ci ](https://github.com/LCAS/hunter_ros2/tree/marc-hanheide-ros-ci)

**Comment by marc-hanheide** [comment]
Sure, done

**Pull request closed without merging**
